export const mockBpList = {
  code: 200,
  msg: 'success',
  data: {
    "pageIndex": 1,
    "pageSize": 10,
    "rows": 0,
    "totalPage":3,
    "totalRecord": 0,
    "data": [
      {
        "id": "string1",
        "userId": 0,
        "measurementDate": "2016-12-26T03:57:34.804Z",
        "systolicPressure": 54,
        "diastolicPressure": 66,
        "heartRate": 0,
        "temperature": 0,
        "created": "2016-12-26T03:57:34.804Z",
        "updated": 0,
        "year": 0,
        "month": 0,
        "day": 0,
        "week": 0,
        "deviceId": "string",
        "userNo": 0,
        "hourPeriod": "string",
        "level": 0,
        "irregularHeartbeat": 0,
        "movementError": 0,
        "ip": "string",
        "deleted": 0,
        "clientid": "string",
        "remark": "string",
        "source": 0
      },
      {
        "id": "string2",
        "userId": 0,
        "measurementDate": "2016-12-26T03:57:34.804Z",
        "systolicPressure": 55,
        "diastolicPressure": 66,
        "heartRate": 0,
        "temperature": 0,
        "created": "2016-12-26T03:57:34.804Z",
        "updated": 0,
        "year": 0,
        "month": 0,
        "day": 0,
        "week": 0,
        "deviceId": "string",
        "userNo": 0,
        "hourPeriod": "string",
        "level": 0,
        "irregularHeartbeat": 0,
        "movementError": 0,
        "ip": "string",
        "deleted": 0,
        "clientid": "string",
        "remark": "string",
        "source": 1
      }
    ]
  }
}
