export default {
  menus: require('./menus').default,
  loading: require('./loading').default,
  login: require('./login').default,
  common: require('./common').default,
  // views
  ...require('../../components/customerLeft/mutations.js').default,
  ...require('.././mutations.js').default,
  ...require('../../views/home/views/customer/bp/mutations.js').default,
  ...require('../../views/home/views/customer/edit/mutations.js').default,
  ...require('../../views/home/views/customer/list/mutations.js').default,
  ...require('../../views/home/views/customer/info/mutations.js').default,
  ...require('../../views/home/views/chat/mutations.js').default,
  ...require('../../views/home/views/chat/record/mutations.js').default,
  ...require('../../views/login/index/mutations.js').default,
  ...require('../../views/home/top/mutations.js').default,
  ...require('../../views/admin/views/doctor/list/mutations.js').default,
  ...require('../../views/admin/views/welcome/mutations.js').default,
  ...require('../../views/admin/views/user/list/mutations.js').default,
  ...require('../../views/admin/views/message/list/mutations.js').default,
  ...require('../../views/admin/views/doctor/info/mutations.js').default,
  ...require('../../views/admin/views/doctor/order/mutations.js').default,
  ...require('../../views/home/views/message/list/mutations').default,
}
